chore(action): return with full script action
Refs: #3

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,11 +29,31 @@ runs:
       env:
         APP_TOKEN: ${{ steps.app-token.outputs.token }}
       run: |
-        curl -L -X GET \
+        CURRENT_VERSION_VAR="${{ inputs.current-version-variable }}"
+        RESPONSE=$(curl -s -f \
           -H "Authorization: Bearer $APP_TOKEN" \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.current-version-variable }}
+          https://api.github.com/repos/${{ github.repository }}/actions/variables/$CURRENT_VERSION_VAR)
+        if [ $? -ne 0 ]; then
+          echo "ERROR: Failed to fetch variable $CURRENT_VERSION_VAR"
+          exit 1
+        fi
+        CURRENT_VERSION=$(echo "$RESPONSE" | jq -r '.value')
+        if [ -z "$CURRENT_VERSION" ]; then
+          echo "ERROR: CURRENT_VERSION repository variable is not set"
+          exit 1
+        fi
+        if ! [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "ERROR: Invalid version format in vars.CURRENT_VERSION $CURRENT_VERSION"
+          exit 1
+        fi
+        IFS="." read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
+        echo "Current version: $CURRENT_VERSION"
+        PATCH=$((PATCH + 1))
+        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
+        echo "New version: $NEW_VERSION"
+        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
       shell: bash
     - name: Update CURRENT_VERSION variable
       env:
@@ -43,6 +63,6 @@ runs:
           -H "Authorization: Bearer $APP_TOKEN" \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/${{ github.repository }}/actions/variables/${{ inputs.current-version-variable }} \
-          -d "{\"name\":\"${{ inputs.current-version-variable }}\",\"value\":\"0.0.1\"}"
+          https://api.github.com/repos/${{ github.repository }}/actions/variables/CURRENT_VERSION \
+          -d "{\"name\":\"CURRENT_VERSION\",\"value\":\"${{ env.NEW_VERSION }}\"}"
       shell: bash
